// import type { Course } from '@/interfaces/course'
import type { Doctor } from "@/interfaces/doctor";

export const data: Array<Doctor> = [
  {
    id: 1,
    cover: "/images/mentors/harshad_purandare.jpeg",
    title: "Dr. Harshad Purandare",
    speciality: "Neuro Surgeon",
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: "Beginner",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-harshad-purandare",
  },
  {
    id: 2,
    cover: "/images/mentors/amit_dhumale.jpeg",
    title: "Dr. Amit Dhumale",
    speciality: "Neuro Rehab",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-amit-dhumale",
  },
  {
    id: 3,
    cover: "/images/mentors/priyank_patel.jpeg",
    title: "Dr. Priyank Patel",
    speciality: "Spine Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 35,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-priyank-patel",
  },
  {
    id: 4,
    cover: "/images/mentors/RajasDeshpande.jpeg",
    title: "Dr. Rajas Deshpande",
    speciality: "Consultant & Director - Neurology",
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: "Intermediate",
    location: "Pune, India",
    hospital: "Jupiter Hospital, Pune",
    pathName: "dr-rajas-deshpande",
  },
  {
    id: 5,
    cover: "/images/mentors/HemantSant.jpeg",
    title: "Dr. Hemant Sant",
    speciality: "Neurology",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Pune, India",
    hospital: "Jupiter Hospital, Pune",
    pathName: "dr-hemant-sant",
  },
  
];
