// import type { Course } from '@/interfaces/course'
import type { Doctor } from "@/interfaces/doctor";

export const data: Array<Doctor> = [
  {
    id: 1,
    cover: "/images/mentors/mangesh.png",
    title: "Dr. Mangesh Kamath",
    speciality: "Oncology",
    rating: 5,
    ratingCount: 8,
    price: 30,
    category: "Beginner",
    location: "Banglore, India",
    hospital: "Fortis Hospital, Banglore",
  },
  {
    id: 2,
    cover: "/images/mentors/SwapnilKapote.jpeg",
    title: "Dr. Swapnil Kapote",
    speciality: "Consultant – Onco Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
  },
  {
    id: 3,
    cover: "/images/mentors/Dayananda.jpeg",
    title: "Dr. Dayanand Srinivasan",
    speciality: "Surgical Oncology",
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: "Intermediate",
    location: "Banglore, India",
    hospital: "Fortis Hospital, Banglore",
  },
  {
    id: 4,
    cover: "/images/mentors/DipanjanHalder.jpeg",
    title: "Dr. Dipanjan Halder",
    speciality: "Haematoncology & BMT",
    rating: 5,
    ratingCount: 15,
    price: 25,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
  },
  {
    id: 5,
    cover: "/images/mentors/harshad_purandare.jpeg",
    title: "Dr. Harshad Purandare",
    speciality: "Neuro Surgeon",
    rating: 5,
    ratingCount: 8,
    price: 30,
    category: "Beginner",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
  },
  {
    id: 6,
    cover: "/images/mentors/amit_dhumale.jpeg",
    title: "Dr. Amit Dhumale",
    speciality: "Neuro Rehab",
    rating: 5,
    ratingCount: 15,
    price: 35,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
  },
  {
    id: 7,
    cover: "/images/mentors/niwrutti.jpeg",
    title: "Dr. Niwrutti Hase",
    speciality: "Director - Nephrology",
    rating: 5,
    ratingCount: 15,
    price: 35,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
  },
  
];
