// import type { Course } from '@/interfaces/course'
import type { Doctor } from "@/interfaces/doctor";

export const data: Array<Doctor> = [
  {
    id: 1,
    cover: "/images/mentors/mangesh.png",
    title: "Dr. Mangesh Kamath",
    speciality: "Oncology",
    rating: 5,
    ratingCount: 8,
    price: 30,
    category: "Beginner",
    location: "Banglore, India",
    hospital: "Fortis Hospital, Banglore",
  },
  {
    id: 2,
    cover: "/images/mentors/Dayananda.jpeg",
    title: "Dr. Dayanand Srinivasan",
    speciality: "Surgical Oncology",
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: "Intermediate",
    location: "Banglore, India",
    hospital: "Fortis Hospital, Banglore",
  },
  {
    id: 3,
    cover: "/images/mentors/indu_bansal-2.jpg",
    title: "Dr. Indu Bansal",
    speciality: "Radiation Oncology",
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: "Beginner",
    location: "Gurugram, India",
    hospital: "Paras Hospital, Gurugram",
  },
  {
    id: 4,
    cover: "/images/mentors/rudra_prasad.jpg",
    title: "Dr. Rudra Prasad Acharya",
    speciality: "Surgical Oncology",
    rating: 5,
    ratingCount: 15,
    price: 40,
    category: "Intermediate",
    location: "Gurugram, India",
    hospital: "Paras Hospital, Gurugram",
  },
];
