// import type { Course } from '@/interfaces/course'
import type { Doctor } from "@/interfaces/doctor";

export const data: Array<Doctor> = [
  {
    id: 1,
    cover: "/images/mentors/ashutosh_singh.jpeg",
    title: "Dr. Ashutosh Singh",
    speciality: "Pediatric Cardiac Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-ashutosh-singh",
  },
  
  {
    id: 2,
    cover: "/images/mentors/amit_dhumale.jpeg",
    title: "Dr. Amit Dhumale",
    speciality: "Neuro Rehab",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-amit-dhumale",
  },
  {
    id: 3,
    cover: "/images/mentors/priyank_patel.jpeg",
    title: "Dr. Priyank Patel",
    speciality: "Spine Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 35,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-priyank-patel",
  },
  {
    id: 4,
    cover: "/images/mentors/harshad_purandare.jpeg",
    title: "Dr. Harshad Purandare",
    speciality: "Neuro Surgeon",
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: "Beginner",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-harshad-purandare",
  },
  {
    id: 5,
    cover: "/images/mentors/taral_nagda.jpeg",
    title: "Dr. Taral Nagda",
    speciality: "Pediatric Orthopedic Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-taral-nagda",
  },
  
];
