// import type { Course } from '@/interfaces/course'
import type { Doctor } from "@/interfaces/doctor";

export const data: Array<Doctor> = [
  {
    id: 1,
    cover: "/images/mentors/ashutosh_singh.jpeg",
    title: "Dr. Ashutosh Singh",
    speciality: "Pediatric Cardiac Surgeon",
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-ashutosh-singh",
  },
  
  {
    id: 2,
    cover: "/images/mentors/NitinBurkule.jpeg",
    title: "Dr. Nitin Burkule",
    speciality: "Consultant - Interventional Cardiologist ",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-nitin-burkule",
  },
  {
    id: 3,
    cover: "/images/mentors/PravinKulkarni.jpeg",
    title: "Dr. Pravin Kulkarni",
    speciality: "CVTS, Heart and Lung Transplant ",
    rating: 5,
    ratingCount: 15,
    price: 35,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-pravin-kulkarni",
  },
  {
    id: 4,
    cover: "/images/mentors/RahulSaraf.jpeg",
    title: "Dr. Rahul Saraf",
    speciality: "Interventional Cardiologist",
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: "Beginner",
    location: "Pune, India",
    hospital: "Jupiter Hospital, Pune",
    pathName: "dr-rahul-saraf",
  },
  {
    id: 5,
    cover: "/images/mentors/GautamRege.jpeg",
    title: "Dr. Gautam Rege",
    speciality: "Consultant - Interventional Cardiologist ",
    rating: 5,
    ratingCount: 15,
    price: 30,
    category: "Intermediate",
    location: "Mumbai, India",
    hospital: "Jupiter Hospital, Mumbai",
    pathName: "dr-gautam-rege",
  },
  
];
